Ss1 114 asynnc
green-fox-academy/DumDum pull request #51
Opened 2022-01-09 17:30 UTC by jakubchoc

async + better DTO

2022-01-10 14:41 UTC, Fronema requested changes
Nechces udelat i servisy async? Ubyo by ti tam tech .Resultu

2022-01-10 14:41 UTC, Fronema commented on DumDum/DumDum/Services/TroopService.cs
>              {
v tomhle a podobnym mistech by bylo lepsi kdybys mel to result natom radku predtim. aby si t tady uz nemusel psat

2022-01-11 09:05 UTC, MatUrb2 approved these changes

2022-01-11 13:19 UTC, marapivas approved these changes

2022-01-12 07:37 UTC, Fronema approved these changes

2022-01-12 12:20 UTC, stmlad approved these changes

2022-01-12 15:58 UTC, Wuwime approved these changes

2022-01-13 08:33 UTC, merged